import type { KnowledgeCaseEvidence } from "./knowledge-synthesis.ts";

export const demoKnowledgeCases: KnowledgeCaseEvidence[] = [
  {
    id: "knowledge-demo-warning-a",
    publicationStatus: "public",
    independentSourceKey: "demo-source-a",
    matchLevel: "exact_specification",
    observations: ["DEMO 警告表示 warning indicator"],
    causeCandidates: ["DEMO 原因候補A（実在情報ではありません）"],
    reportedChecks: ["DEMO 確認箇所A（実在情報ではありません）"],
    reportedActions: ["DEMO 対応A（具体的作業ではありません）"],
    reportedParts: ["DEMO 交換部品A（実在情報ではありません）"],
    outcome: "improved",
    verificationStatus: "owner_confirmed",
    hazardTags: [],
    hazardLevel: "CAUTION",
    sourceTitle: "DEMO: 雨上がりの短いドライブ",
    sourceHref: "/journal/journal-demo-luca-drive",
    sourceKind: "journal",
  },
  {
    id: "knowledge-demo-warning-b",
    publicationStatus: "public",
    independentSourceKey: "demo-source-b",
    matchLevel: "same_model_other_year",
    observations: ["DEMO 警告表示 warning indicator"],
    causeCandidates: ["DEMO 原因候補A（実在情報ではありません）"],
    reportedChecks: ["DEMO 確認箇所B（実在情報ではありません）"],
    reportedActions: ["DEMO 対応B（具体的作業ではありません）"],
    reportedParts: [],
    outcome: "unresolved",
    verificationStatus: "unconfirmed",
    hazardTags: [],
    hazardLevel: "CAUTION",
    sourceTitle: "DEMO: 入庫前に履歴が見えると助かること",
    sourceHref: "/journal/journal-demo-workshop-history",
    sourceKind: "journal",
  },
  {
    id: "knowledge-demo-safety",
    publicationStatus: "public",
    independentSourceKey: "demo-source-c",
    matchLevel: "general_symptom",
    observations: ["DEMO 安全に関わる症状 safety critical symptom"],
    causeCandidates: ["DEMO 安全領域の原因候補（実在情報ではありません）"],
    reportedChecks: ["DEMO 専門家確認が必要な例"],
    reportedActions: [],
    reportedParts: [],
    outcome: "unknown",
    verificationStatus: "unconfirmed",
    hazardTags: ["brakes"],
    hazardLevel: "CRITICAL",
    sourceTitle: "安全領域の構造化事例（DEMO）",
    sourceHref: "/search",
    sourceKind: "structured_case",
  },
];
