import type { AppData } from "./types.ts";

export const demoData: AppData = {
  schemaVersion: 10,
  vehicles: [
    {
      id: "vehicle-demo-barchetta",
      ownerProfileId: "profile-demo-current",
      vehicleCategory: "car",
      make: "FIAT",
      model: "Barchetta",
      makeInput: "FIAT",
      modelInput: "Barchetta",
      brandId: "fiat",
      modelFamilyId: "fiat-barchetta",
      marketNameId: "fiat-barchetta-global",
      marketRegion: "global",
      identityMatchStatus: "matched_alias",
      year: 1997,
      ownershipType: "owned",
      ownershipStartedYear: 2014,
      ownershipStartedMonth: 4,
      engine: "1.8 16V",
      steering: "LHD",
      transmission: "5MT",
      odometerKm: 86420,
      odometerEpisodes: [
        { id: "episode-demo-1", reason: "initial", startedAt: "1997-01-01" },
        { id: "episode-demo-2", reason: "replacement", previousEpisodeId: "episode-demo-1" },
        { id: "episode-demo-3", reason: "replacement", previousEpisodeId: "episode-demo-2" },
        { id: "episode-demo-4", reason: "replacement", previousEpisodeId: "episode-demo-3" },
      ],
      currentOdometerReading: {
        episodeId: "episode-demo-4",
        displayedValue: 86420,
        unit: "km",
        sequenceAssessment: "consistent_increase",
      },
      odometerContext: "current",
      imagePath: "/demo-roadster.png",
      isDemo: true,
    },
  ],
  records: [
    {
      id: "record-demo-oil",
      vehicleId: "vehicle-demo-barchetta",
      serviceDate: "2026-04-12",
      odometerKm: 85200,
      odometerReading: {
        episodeId: "episode-demo-4",
        displayedValue: 85200,
        unit: "km",
        sequenceAssessment: "consistent_increase",
      },
      summary: "DEMO: エンジンオイルの定期記録",
      sourceLanguage: "ja",
      demoTranslation: { en: "DEMO: Routine engine oil record" },
      symptoms: "サンプル記録のため、症状情報はありません。",
      causeCandidates: "該当なし",
      checksPerformed: "定期記録として入力したデモ項目です。",
      workPerformed: "具体的な作業手順を含まないデモ記録です。",
      parts: [{ name: "DEMO: 消耗品（部品番号なし）" }],
      cost: 0,
      resolutionStatus: "resolved",
      hazardLevel: "LOW",
      visibility: "private",
      verificationStatus: "owner_confirmed",
      sourceType: "demo",
      evidenceBasis: "unknown",
      matchScope: "DEMO vehicle only",
      result: "デモ表示用の完了状態です。実在する整備結果ではありません。",
      actions: [
        {
          id: "action-demo-oil",
          summary: "DEMO: 定期記録",
          causeCandidates: "該当なし",
          checksPerformed: "定期記録として入力したデモ項目です。",
          workPerformed: "具体的な作業手順を含まないデモ記録です。",
          parts: [{ name: "DEMO: 消耗品（部品番号なし）" }],
          result: "デモ表示用の完了状態です。実在する整備結果ではありません。",
          resolutionStatus: "resolved",
          hazardLevel: "LOW",
        },
        {
          id: "action-demo-oil-secondary",
          summary: "DEMO: 同じ入庫での追加点検",
          causeCandidates: "該当なし",
          checksPerformed: "複数作業表示を確認するための抽象的なDEMO項目です。",
          workPerformed: "具体的な点検箇所や作業手順は含みません。",
          parts: [],
          result: "操作確認用の完了状態です。実在する点検結果ではありません。",
          resolutionStatus: "resolved",
          hazardLevel: "LOW",
        },
      ],
      createdAt: "2026-04-12T09:00:00.000Z",
      updatedAt: "2026-04-12T09:00:00.000Z",
      isDemo: true,
    },
    {
      id: "record-demo-tire",
      vehicleId: "vehicle-demo-barchetta",
      serviceDate: "2026-05-28",
      odometerKm: 86010,
      odometerReading: {
        episodeId: "episode-demo-4",
        displayedValue: 86010,
        unit: "km",
        sequenceAssessment: "consistent_increase",
      },
      summary: "DEMO: タイヤ状態の確認メモ",
      sourceLanguage: "ja",
      demoTranslation: { en: "DEMO: Tire condition check note" },
      symptoms: "サンプルの状態確認メモです。",
      causeCandidates: "原因候補は記録していません。",
      checksPerformed: "外観状態を確認したという想定のデモです。",
      workPerformed: "作業手順は含みません。",
      parts: [],
      resolutionStatus: "resolved",
      hazardLevel: "CAUTION",
      visibility: "pending_review",
      verificationStatus: "owner_confirmed",
      sourceType: "demo",
      evidenceBasis: "unknown",
      matchScope: "DEMO vehicle only",
      result: "確認済み表示を試すためのサンプルです。",
      actions: [
        {
          id: "action-demo-tire",
          summary: "DEMO: 状態確認",
          causeCandidates: "原因候補は記録していません。",
          checksPerformed: "外観状態を確認したという想定のデモです。",
          workPerformed: "作業手順は含みません。",
          parts: [],
          result: "確認済み表示を試すためのサンプルです。",
          resolutionStatus: "resolved",
          hazardLevel: "CAUTION",
        },
      ],
      createdAt: "2026-05-28T09:00:00.000Z",
      updatedAt: "2026-05-28T09:00:00.000Z",
      isDemo: true,
    },
    {
      id: "record-demo-warning",
      vehicleId: "vehicle-demo-barchetta",
      serviceDate: "2026-06-19",
      odometerKm: 86390,
      odometerReading: {
        episodeId: "episode-demo-4",
        displayedValue: 86390,
        unit: "km",
        sequenceAssessment: "consistent_increase",
      },
      summary: "DEMO: 原因未確認の警告表示メモ",
      sourceLanguage: "ja",
      demoTranslation: { en: "DEMO: Unconfirmed warning indicator note" },
      symptoms: "警告表示を確認したという想定のサンプルです。",
      causeCandidates: "未確認。原因を断定しません。",
      checksPerformed: "確認内容はまだ登録されていません。",
      workPerformed: "作業は実施していない想定です。",
      parts: [],
      resolutionStatus: "unresolved",
      hazardLevel: "CRITICAL",
      visibility: "private",
      verificationStatus: "unconfirmed",
      sourceType: "demo",
      evidenceBasis: "unknown",
      matchScope: "DEMO vehicle only",
      result: "未解決。専門家への相談を促す表示確認用です。",
      actions: [
        {
          id: "action-demo-warning",
          summary: "DEMO: 未実施",
          causeCandidates: "未確認。原因を断定しません。",
          checksPerformed: "確認内容はまだ登録されていません。",
          workPerformed: "作業は実施していない想定です。",
          parts: [],
          result: "未解決。専門家への相談を促す表示確認用です。",
          resolutionStatus: "unresolved",
          hazardLevel: "CRITICAL",
        },
      ],
      createdAt: "2026-06-19T09:00:00.000Z",
      updatedAt: "2026-06-19T09:00:00.000Z",
      isDemo: true,
    },
  ],
  profiles: [
    {
      id: "profile-demo-current",
      displayName: "DEMO Owner",
      role: "owner",
      bio: "自分の車両履歴を整理しているDEMOプロフィールです。",
      visibility: "private",
      displayFields: ["role", "bio", "vehicles", "ownership_duration", "journal_count"],
      isProfessional: false,
      isDemo: true,
    },
    {
      id: "profile-demo-luca",
      displayName: "Luca / DEMO",
      role: "owner",
      bio: "Barchettaとの日々を記録するDEMOオーナーです。",
      visibility: "public",
      displayFields: ["role", "bio", "vehicles", "ownership_duration", "journal_count"],
      isProfessional: false,
      isDemo: true,
    },
    {
      id: "profile-demo-workshop",
      displayName: "Officina Verde / DEMO",
      role: "mechanic",
      bio: "車両履歴を確認してから相談を受けるDEMO Professionalです。",
      visibility: "public",
      displayFields: ["role", "bio", "journal_count"],
      isProfessional: true,
      isDemo: true,
    },
  ],
  currentProfileId: "profile-demo-current",
  journals: [
    {
      id: "journal-demo-owner-private",
      authorProfileId: "profile-demo-current",
      vehicleId: "vehicle-demo-barchetta",
      vehicleTargetId: "vehicle-demo-barchetta",
      vehicleLabel: "FIAT Barchetta",
      modelTargetId: "model-family:fiat-barchetta",
      title: "DEMO: 今年の記録を整理しはじめた",
      bodyOriginal:
        "紙に残っていた記録を見返しながら、分かる範囲だけ入力している。まずは後から自分が困らない履歴にしたい。",
      sourceLanguage: "ja",
      visibility: "private",
      moderationState: "visible",
      linkedRecordId: "record-demo-oil",
      displayFields: ["service_date", "odometer", "actions"],
      media: [],
      contentBlocks: [
        {
          id: "journal-block-demo-owner-private-text",
          type: "text",
          style: "paragraph",
          text: "紙に残っていた記録を見返しながら、分かる範囲だけ入力している。まずは後から自分が困らない履歴にしたい。",
        },
      ],
      knowledgeExtractionConsent: false,
      appreciationCount: 0,
      createdAt: "2026-07-10T09:00:00.000Z",
      updatedAt: "2026-07-10T09:00:00.000Z",
      isDemo: true,
    },
    {
      id: "journal-demo-luca-drive",
      authorProfileId: "profile-demo-luca",
      vehicleTargetId: "vehicle-demo-luca-barchetta",
      vehicleLabel: "FIAT Barchetta",
      modelTargetId: "model-family:fiat-barchetta",
      title: "DEMO: 雨上がりの短いドライブ",
      bodyOriginal:
        "整備を終えてから初めての週末。遠くへは行かず、近所をゆっくり走って様子を見た。帰ってから気づいたことを記録へ追記した。",
      sourceLanguage: "ja",
      visibility: "public",
      moderationState: "visible",
      displayFields: [],
      media: [
        {
          id: "media-demo-roadster",
          kind: "image",
          source: "demo_asset",
          assetPath: "/demo-roadster.png",
          mimeType: "image/png",
          sizeBytes: 0,
          altText: "DEMO: 屋外に停めたオープンカーのサンプル画像",
          privacyState: "public_ready",
          createdAt: "2026-07-12T08:30:00.000Z",
          isDemo: true,
        },
      ],
      contentBlocks: [
        {
          id: "journal-block-demo-luca-intro",
          type: "text",
          style: "paragraph",
          text: "整備を終えてから初めての週末。遠くへは行かず、近所をゆっくり走って様子を見た。",
        },
        {
          id: "journal-block-demo-luca-photo",
          type: "media",
          mediaId: "media-demo-roadster",
        },
        {
          id: "journal-block-demo-luca-outro",
          type: "text",
          style: "paragraph",
          text: "帰ってから気づいたことを記録へ追記した。止まったことも、直ったことも、このクルマとの続きをつくる一日として残しておく。",
        },
      ],
      knowledgeExtractionConsent: true,
      appreciationCount: 14,
      createdAt: "2026-07-12T08:30:00.000Z",
      updatedAt: "2026-07-12T08:30:00.000Z",
      publishedAt: "2026-07-12T08:30:00.000Z",
      isDemo: true,
    },
    {
      id: "journal-demo-workshop-history",
      authorProfileId: "profile-demo-workshop",
      vehicleTargetId: "vehicle-demo-workshop-barchetta",
      vehicleLabel: "FIAT Barchetta",
      modelTargetId: "model-family:fiat-barchetta",
      title: "DEMO: 入庫前に履歴が見えると助かること",
      bodyOriginal:
        "初めて扱う車種でも、過去の作業と未解決事項が整理されていれば、確認の順序を考えやすい。これは操作確認用の文章で、修理方法を示すものではない。",
      sourceLanguage: "ja",
      visibility: "public",
      moderationState: "visible",
      displayFields: [],
      media: [],
      contentBlocks: [
        {
          id: "journal-block-demo-workshop-text",
          type: "text",
          style: "paragraph",
          text: "初めて扱う車種でも、過去の作業と未解決事項が整理されていれば、確認の順序を考えやすい。これは操作確認用の文章で、修理方法を示すものではない。",
        },
      ],
      knowledgeExtractionConsent: false,
      appreciationCount: 8,
      createdAt: "2026-07-11T11:00:00.000Z",
      updatedAt: "2026-07-11T11:00:00.000Z",
      publishedAt: "2026-07-11T11:00:00.000Z",
      isDemo: true,
    },
  ],
  follows: [
    {
      id: "follow-demo-profile-luca",
      followerProfileId: "profile-demo-current",
      targetType: "profile",
      targetId: "profile-demo-luca",
      createdAt: "2026-07-12T07:00:00.000Z",
    },
    {
      id: "follow-demo-model-barchetta",
      followerProfileId: "profile-demo-current",
      targetType: "model",
      targetId: "model-family:fiat-barchetta",
      createdAt: "2026-07-12T07:00:00.000Z",
    },
  ],
  profileSafetyRelations: [],
  contentReports: [],
};

export function cloneDemoData(): AppData {
  return structuredClone(demoData);
}
