import type { AppData } from "./types.ts";

export const demoData: AppData = {
  vehicles: [
    {
      id: "vehicle-demo-barchetta",
      make: "FIAT",
      model: "Barchetta",
      year: 1997,
      engine: "1.8 16V",
      steering: "LHD",
      transmission: "5MT",
      odometerKm: 86420,
      imagePath: "/demo-roadster.png",
      isDemo: true,
    },
  ],
  records: [
    {
      id: "record-demo-oil",
      vehicleId: "vehicle-demo-barchetta",
      serviceDate: "2026-04-12",
      odometerKm: 85200,
      summary: "DEMO: エンジンオイルの定期記録",
      sourceLanguage: "ja",
      demoTranslation: { en: "DEMO: Routine engine oil record" },
      symptoms: "サンプル記録のため、症状情報はありません。",
      causeCandidates: "該当なし",
      checksPerformed: "定期記録として入力したデモ項目です。",
      workPerformed: "具体的な作業手順を含まないデモ記録です。",
      parts: [{ name: "DEMO: 消耗品（部品番号なし）" }],
      cost: 0,
      resolutionStatus: "resolved",
      hazardLevel: "LOW",
      visibility: "private",
      verificationStatus: "owner_confirmed",
      sourceType: "demo",
      matchScope: "DEMO vehicle only",
      result: "デモ表示用の完了状態です。実在する整備結果ではありません。",
      createdAt: "2026-04-12T09:00:00.000Z",
      updatedAt: "2026-04-12T09:00:00.000Z",
      isDemo: true,
    },
    {
      id: "record-demo-tire",
      vehicleId: "vehicle-demo-barchetta",
      serviceDate: "2026-05-28",
      odometerKm: 86010,
      summary: "DEMO: タイヤ状態の確認メモ",
      sourceLanguage: "ja",
      demoTranslation: { en: "DEMO: Tire condition check note" },
      symptoms: "サンプルの状態確認メモです。",
      causeCandidates: "原因候補は記録していません。",
      checksPerformed: "外観状態を確認したという想定のデモです。",
      workPerformed: "作業手順は含みません。",
      parts: [],
      resolutionStatus: "resolved",
      hazardLevel: "CAUTION",
      visibility: "pending_review",
      verificationStatus: "owner_confirmed",
      sourceType: "demo",
      matchScope: "DEMO vehicle only",
      result: "確認済み表示を試すためのサンプルです。",
      createdAt: "2026-05-28T09:00:00.000Z",
      updatedAt: "2026-05-28T09:00:00.000Z",
      isDemo: true,
    },
    {
      id: "record-demo-warning",
      vehicleId: "vehicle-demo-barchetta",
      serviceDate: "2026-06-19",
      odometerKm: 86390,
      summary: "DEMO: 原因未確認の警告表示メモ",
      sourceLanguage: "ja",
      demoTranslation: { en: "DEMO: Unconfirmed warning indicator note" },
      symptoms: "警告表示を確認したという想定のサンプルです。",
      causeCandidates: "未確認。原因を断定しません。",
      checksPerformed: "確認内容はまだ登録されていません。",
      workPerformed: "作業は実施していない想定です。",
      parts: [],
      resolutionStatus: "unresolved",
      hazardLevel: "CRITICAL",
      visibility: "private",
      verificationStatus: "unconfirmed",
      sourceType: "demo",
      matchScope: "DEMO vehicle only",
      result: "未解決。専門家への相談を促す表示確認用です。",
      createdAt: "2026-06-19T09:00:00.000Z",
      updatedAt: "2026-06-19T09:00:00.000Z",
      isDemo: true,
    },
  ],
};

export function cloneDemoData(): AppData {
  return structuredClone(demoData);
}
