import type { KnowledgeCaseEvidence } from "./knowledge-synthesis.ts";

export const demoKnowledgeCases: KnowledgeCaseEvidence[] = [
  {
    id: "knowledge-demo-warning-a",
    publicationStatus: "public",
    independentSourceKey: "demo-source-a",
    matchLevel: "exact_specification",
    observations: ["DEMO 警告表示 warning indicator"],
    causeCandidates: ["DEMO 原因候補A（実在情報ではありません）"],
    reportedChecks: ["DEMO 確認箇所A（実在情報ではありません）"],
    reportedActions: ["DEMO 対応A（具体的作業ではありません）"],
    outcome: "improved",
    verificationStatus: "owner_confirmed",
    hazardTags: [],
    hazardLevel: "CAUTION",
  },
  {
    id: "knowledge-demo-warning-b",
    publicationStatus: "public",
    independentSourceKey: "demo-source-b",
    matchLevel: "same_model_other_year",
    observations: ["DEMO 警告表示 warning indicator"],
    causeCandidates: ["DEMO 原因候補A（実在情報ではありません）"],
    reportedChecks: ["DEMO 確認箇所B（実在情報ではありません）"],
    reportedActions: ["DEMO 対応B（具体的作業ではありません）"],
    outcome: "unresolved",
    verificationStatus: "unconfirmed",
    hazardTags: [],
    hazardLevel: "CAUTION",
  },
  {
    id: "knowledge-demo-safety",
    publicationStatus: "public",
    independentSourceKey: "demo-source-c",
    matchLevel: "general_symptom",
    observations: ["DEMO 安全に関わる症状 safety critical symptom"],
    causeCandidates: ["DEMO 安全領域の原因候補（実在情報ではありません）"],
    reportedChecks: ["DEMO 専門家確認が必要な例"],
    reportedActions: [],
    outcome: "unknown",
    verificationStatus: "unconfirmed",
    hazardTags: ["brakes"],
    hazardLevel: "CRITICAL",
  },
];
